export enum LANGUAGE {
  ENGLISH = "en",
  ARABIC = "ar",
  CATALAN = "ca",
  CZECH = "cs",
  DANISH = "da",
  GERMAN = "de",
  GREEK = "el",
  SPANISH = "es",
  SLOVAKIAN = "sk",
  FRENCH = "fr",
  HEBREW = "he",
  HINDI = "hi",
  HUNGARIAN = "hu",
  INDONESIAN = "id",
  ITALIAN = "it",
  JAPANESE = "ja",
  KOREAN = "ko",
  DUTCH = "nl",
  BOKMAL = "nb",
  POLISH = "pl",
  PORTUGUESE = "pt",
  RUSSIAN = "ru",
  SWEDISH = "sv",
  THAI = "th",
  TURKISH = "tr",
  VIETNAMESE = "vi",
  CHINESE = "zh",
}

export enum LANGUAGE_NAMES {
  "en" = "English",
  "ar" = "Arabic",
  "ca" = "Catalan",
  "cs" = "Czech",
  "da" = "Danish",
  "de" = "German",
  "el" = "Greek",
  "es" = "Spanish",
  "sk" = "Slovakian",
  "fr" = "French",
  "he" = "Hebrew",
  "hi" = "Hindi",
  "hu" = "Hungarian",
  "id" = "Indonesian",
  "it" = "Italian",
  "ja" = "Japanese",
  "ko" = "Korean",
  "nl" = "Dutch",
  "nb" = "Bokmal",
  "pl" = "Polish",
  "pt" = "Portuguese",
  "ru" = "Russian",
  "sv" = "Swedish",
  "th" = "Thai",
  "tr" = "Turkish",
  "vi" = "Vietnamese",
  "zh" = "Chinese",
}

export type I18nText = {
  [language in LANGUAGE as string]?: string;
};
