FROM node:lts-alpine as app-base

WORKDIR /usr/src/app

COPY ./package.json ./

EXPOSE 3000

RUN yarn

FROM app-base:latest as build-deps

ARG ENV_FILE

COPY . .

RUN yarn && cp $ENV_FILE .env && yarn build

FROM nginx:alpine

COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]